/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"

#define MAX_LIBROS 10000

TLibro *Biblioteca = NULL;

int numLibros = 0;
int tam = 0;
int idAdmin = -1;
Cadena nameFich = "";
int campoOrd = 0;

  // Convertir pass a una cadena de caracteres
  // char pass_str[10];
  // sprintf(pass_str, "%d", pass);

  // Imprimir el valor de pass utilizando perror
  // perror("El valor de pass es");
  // perror(pass_str);


int *
conexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int pass = *argp;
	if(pass != 1234){
		result = -2;
	}else if(idAdmin != -1){
		result = -1;
	}else{
		idAdmin = 1 + rand() % RAND_MAX;
		result = idAdmin;
		Biblioteca = (TLibro *) malloc(sizeof(TLibro)*numLibros);
	}


	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
cargardatos_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	printf("Ejecucion cargar datos servidor");
	static int  result;
	FILE *archivo = fopen(argp->Datos, "rb");
	
	const int idAdminC = argp-> Ida;
	
	TLibro libro = {};
	
	if(idAdmin != idAdminC){
		result = -1;
	}else{
		if(archivo == NULL){
			result = -1;
		
		}
		
		fread(&numLibros, sizeof(numLibros), 1, archivo);
		
		
		
		if(Biblioteca == NULL){
			perror("ERROR: No se ha reservado memoria para la biblioteca");
		}else{
		
			fread(Biblioteca, sizeof(libro) * numLibros, numLibros, archivo);
		}
		fclose(archivo);
		
		result = numLibros;
	
	}
	
	return &result;
}

bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;

	TLibro nuevoLibro = argp->Libro;
	
	if(Biblioteca == NULL){
		result = -1;
	}else{
			
		if(numLibros < MAX_LIBROS)
		{
			Biblioteca[numLibros] = nuevoLibro;
			numLibros++;
			result = 1;
		}else result = 0;	
	}
	

	
	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}



