/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"

#define MAX_LIBROS 100

TLibro *Biblioteca = NULL;

int numLibros = 0;
int tam = 0;
int idAdmin = -1;
Cadena nameFich = "";
int campoOrd = 0;


int *
conexion_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
cargardatos_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	printf("Ejecucion cargar datos servidor");
	static int  result;
	FILE *archivo = fopen(argp->Datos, "rb");
	
	if(archivo == NULL){
		perror("Error al abrir el archivo");
	result = -1;
	
	}else{
		
	TLibro libros[MAX_LIBROS];
	int nLibros = 0;

	while(nLibros <MAX_LIBROS && fread(&libros[nLibros], sizeof(TLibro), 1, archivo))
		nLibros++;

	fclose(archivo);

	result = nLibros;
	printf("Numero de libros cargados: %d.\n",result);

	}

	return &result;
}

bool_t *
guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;

	TLibro nuevoLibro = argp->Libro;
	
	if(numLibros < MAX_LIBROS)
	{
		Biblioteca[numLibros] = nuevoLibro;
		numLibros++;
	result = 1;
	}else result = 0;
	
	return &result;
}

int *
comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TLibro *
descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}



